Revert "msm: camera: reqmgr: Remove unused variable"
Else Build Fails on davinci:
This reverts commit 71284cc74c2fb5401ac9df06c2778c4d8e6ef720.

/home/rom/r/kernel/xiaomi/sm6150/drivers/media/platform/msm/camera/cam_req_mgr/cam_req_mgr_core.c:2014:4: error: use of undeclared identifier 'tbl'
                        tbl = link->req.l_tbl;
                        ^
/home/rom/r/kernel/xiaomi/sm6150/drivers/media/platform/msm/camera/cam_req_mgr/cam_req_mgr_core.c:2016:11: error: use of undeclared identifier 'tbl'
                        while (tbl != NULL) {
                               ^
/home/rom/r/kernel/xiaomi/sm6150/drivers/media/platform/msm/camera/cam_req_mgr/cam_req_mgr_core.c:2018:18: error: use of undeclared identifier 'tbl'
                                        tbl->pd, i, tbl->slot[i].state);
                                                    ^
/home/rom/r/kernel/xiaomi/sm6150/drivers/media/platform/msm/camera/cam_req_mgr/cam_req_mgr_core.c:2018:6: error: use of undeclared identifier 'tbl'
                                        tbl->pd, i, tbl->slot[i].state);
                                        ^
/home/rom/r/kernel/xiaomi/sm6150/drivers/media/platform/msm/camera/cam_req_mgr/cam_req_mgr_core.c:2019:6: error: use of undeclared identifier 'tbl'
                                 tbl->slot[i].req_ready_map = 0;
                                 ^
/home/rom/r/kernel/xiaomi/sm6150/drivers/media/platform/msm/camera/cam_req_mgr/cam_req_mgr_core.c:2020:6: error: use of undeclared identifier 'tbl'
                                 tbl->slot[i].dev_hdl = -1;
                                 ^
/home/rom/r/kernel/xiaomi/sm6150/drivers/media/platform/msm/camera/cam_req_mgr/cam_req_mgr_core.c:2021:6: error: use of undeclared identifier 'tbl'
                                 tbl->slot[i].skip_next_frame = false;
                                 ^
/home/rom/r/kernel/xiaomi/sm6150/drivers/media/platform/msm/camera/cam_req_mgr/cam_req_mgr_core.c:2022:6: error: use of undeclared identifier 'tbl'
                                 tbl->slot[i].state = CRM_REQ_STATE_EMPTY;
                                 ^
/home/rom/r/kernel/xiaomi/sm6150/drivers/media/platform/msm/camera/cam_req_mgr/cam_req_mgr_core.c:2023:6: error: use of undeclared identifier 'tbl'
                                 tbl->slot[i].is_applied = false;
                                 ^
/home/rom/r/kernel/xiaomi/sm6150/drivers/media/platform/msm/camera/cam_req_mgr/cam_req_mgr_core.c:2024:6: error: use of undeclared identifier 'tbl'
                                 tbl = tbl->next;
                                 ^
/home/rom/r/kernel/xiaomi/sm6150/drivers/media/platform/msm/camera/cam_req_mgr/cam_req_mgr_core.c:2024:12: error: use of undeclared identifier 'tbl'
                                 tbl = tbl->next;
                                       ^
11 errors generated.